<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ConsultasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('consultas')->insert([
    ['id' => 1, 'cita_id' => 9, 'doctor_id' => 21, 'paciente_id' => 57, 'motivo' => 'Dolor de pansa', 'sintomas' => 'Voluptatem et incidunt quas nam et suscipit.', 'diagnostico' => 'Nam qui quos omnis voluptatem voluptas quibusdam voluptatibus.', 'notas_clinicas' => 'Rerum libero nam sequi. Eligendi ut vero a qui. Sit exercitationem et blanditiis. Rerum enim modi illo molestiae veritatis mollitia.', 'examen' => null, 'fecha_tratamiento' => null, 'created_at' => '2026-03-26 09:05:46', 'updated_at' => '2026-03-26 09:05:46'],
    ['id' => 2, 'cita_id' => 10, 'doctor_id' => 21, 'paciente_id' => 58, 'motivo' => null, 'sintomas' => 'Magnam voluptatem voluptas quas cupiditate.', 'diagnostico' => 'Ea modi amet id consequuntur ut perferendis voluptas aut.', 'notas_clinicas' => 'Sapiente nostrum quo quas qui accusamus. Id illum quibusdam ratione sit quaerat. Mollitia id eveniet animi nisi quidem.', 'examen' => null, 'fecha_tratamiento' => null, 'created_at' => '2026-03-26 09:05:46', 'updated_at' => '2026-03-26 09:05:46'],
    ['id' => 3, 'cita_id' => 14, 'doctor_id' => 20, 'paciente_id' => 62, 'motivo' => null, 'sintomas' => 'Ut eum excepturi nulla vel mollitia et.', 'diagnostico' => 'Eos et officiis tempora rerum quidem est tenetur nulla.', 'notas_clinicas' => 'Quia repudiandae est sit. Mollitia sunt consectetur velit delectus molestiae nostrum. Iusto pariatur quia ducimus qui ut dolore.', 'examen' => null, 'fecha_tratamiento' => null, 'created_at' => '2026-03-26 09:05:46', 'updated_at' => '2026-03-26 09:05:46'],
    ['id' => 4, 'cita_id' => 15, 'doctor_id' => 21, 'paciente_id' => 63, 'motivo' => null, 'sintomas' => 'Et quisquam id nihil voluptas ut.', 'diagnostico' => 'Rerum ea et velit repellendus.', 'notas_clinicas' => 'Consequatur sint beatae nostrum quo. In repellat vel eveniet quo. Sed est nulla repellat sit est. Eum laboriosam earum aliquam dolorem nisi.', 'examen' => null, 'fecha_tratamiento' => null, 'created_at' => '2026-03-26 09:05:46', 'updated_at' => '2026-03-26 09:05:46'],
    ['id' => 5, 'cita_id' => 18, 'doctor_id' => 16, 'paciente_id' => 66, 'motivo' => null, 'sintomas' => 'Optio commodi provident voluptatem eos quidem veritatis.', 'diagnostico' => 'Ullam consectetur quia officiis neque delectus culpa totam.', 'notas_clinicas' => 'Sed commodi eveniet maxime nesciunt accusamus corporis quis sit. Velit ullam rerum fuga dolorem illum omnis libero. Quia quo voluptatum doloremque facere. Voluptatum odit voluptas ea et vitae.', 'examen' => null, 'fecha_tratamiento' => null, 'created_at' => '2026-03-26 09:05:46', 'updated_at' => '2026-03-26 09:05:46'],
    ['id' => 6, 'cita_id' => 25, 'doctor_id' => 25, 'paciente_id' => 73, 'motivo' => null, 'sintomas' => 'Quisquam aut animi ipsam omnis quia est.', 'diagnostico' => 'Exercitationem et eum nihil facere totam ex et.', 'notas_clinicas' => 'Id doloremque ut explicabo minima itaque qui voluptas. Omnis qui eaque omnis error omnis occaecati voluptas. Unde magni iusto sed nihil voluptate. Hic sed voluptatem repudiandae qui voluptatem.', 'examen' => null, 'fecha_tratamiento' => null, 'created_at' => '2026-03-26 09:05:46', 'updated_at' => '2026-03-26 09:05:46'],
    ['id' => 7, 'cita_id' => 28, 'doctor_id' => 19, 'paciente_id' => 76, 'motivo' => null, 'sintomas' => 'Et sapiente voluptatem qui voluptatem est rerum dignissimos.', 'diagnostico' => 'Placeat adipisci magnam sequi ut.', 'notas_clinicas' => 'Optio sapiente tenetur nulla assumenda vero. Repellat rerum odit eum et doloribus tempora. Rerum vel voluptates provident molestias. Delectus mollitia ea quia corrupti veniam.', 'examen' => null, 'fecha_tratamiento' => null, 'created_at' => '2026-03-26 09:05:46', 'updated_at' => '2026-03-26 09:05:46'],
    ['id' => 8, 'cita_id' => 34, 'doctor_id' => 16, 'paciente_id' => 82, 'motivo' => null, 'sintomas' => 'Porro et quae cupiditate quae pariatur est.', 'diagnostico' => 'Vel est pariatur inventore non harum natus quod ratione.', 'notas_clinicas' => 'Ipsa laboriosam neque aut ullam explicabo facere omnis. Amet qui at atque provident. Libero est quia dolores.', 'examen' => null, 'fecha_tratamiento' => null, 'created_at' => '2026-03-26 09:05:46', 'updated_at' => '2026-03-26 09:05:46'],
    ['id' => 9, 'cita_id' => 42, 'doctor_id' => 22, 'paciente_id' => 90, 'motivo' => null, 'sintomas' => 'Adipisci voluptatem repudiandae quia.', 'diagnostico' => 'Illum et qui ea odio maxime.', 'notas_clinicas' => 'Nemo occaecati voluptatem est fuga magni delectus ducimus. Minima ut nihil fugit ut. Et earum esse dolor.', 'examen' => null, 'fecha_tratamiento' => null, 'created_at' => '2026-03-26 09:05:46', 'updated_at' => '2026-03-26 09:05:46'],
    ['id' => 10, 'cita_id' => 44, 'doctor_id' => 21, 'paciente_id' => 92, 'motivo' => null, 'sintomas' => 'Vero assumenda nam voluptas exercitationem eligendi porro sit.', 'diagnostico' => 'Voluptatem omnis fugiat quae.', 'notas_clinicas' => 'Quia eum voluptas voluptate. Impedit atque aspernatur et minus soluta. Autem temporibus praesentium sunt sunt voluptate maxime minima.', 'examen' => null, 'fecha_tratamiento' => null, 'created_at' => '2026-03-26 09:05:46', 'updated_at' => '2026-03-26 09:05:46'],
    ['id' => 11, 'cita_id' => 45, 'doctor_id' => 23, 'paciente_id' => 93, 'motivo' => null, 'sintomas' => 'Vero at quae at eos.', 'diagnostico' => 'Animi facere qui qui exercitationem et tenetur.', 'notas_clinicas' => 'Aliquid illo praesentium dolor quo aspernatur. Occaecati voluptatem neque ipsam voluptates sed consequatur.', 'examen' => null, 'fecha_tratamiento' => null, 'created_at' => '2026-03-26 09:05:46', 'updated_at' => '2026-03-26 09:05:46'],
    ['id' => 12, 'cita_id' => 46, 'doctor_id' => 23, 'paciente_id' => 94, 'motivo' => null, 'sintomas' => 'A minima sed iusto aut dolores.', 'diagnostico' => 'Sequi error architecto delectus praesentium molestiae eum.', 'notas_clinicas' => 'Distinctio praesentium est magnam commodi ullam repellat. Aliquam culpa maiores saepe in. Rerum adipisci accusantium et eveniet voluptas quasi. Ducimus quam aut fuga non sunt quasi.', 'examen' => null, 'fecha_tratamiento' => null, 'created_at' => '2026-03-26 09:05:46', 'updated_at' => '2026-03-26 09:05:46'],
    ['id' => 13, 'cita_id' => 48, 'doctor_id' => 21, 'paciente_id' => 96, 'motivo' => null, 'sintomas' => 'Impedit quo pariatur voluptatem possimus velit.', 'diagnostico' => 'Aspernatur aperiam maxime atque commodi nihil.', 'notas_clinicas' => 'Nostrum assumenda ut qui molestiae et facilis. Nostrum incidunt harum et amet id. Velit eos placeat possimus rerum. Illum est delectus optio est facere tempore.', 'examen' => null, 'fecha_tratamiento' => null, 'created_at' => '2026-03-26 09:05:46', 'updated_at' => '2026-03-26 09:05:46'],
    ['id' => 14, 'cita_id' => 50, 'doctor_id' => 20, 'paciente_id' => 98, 'motivo' => null, 'sintomas' => 'Laudantium reiciendis temporibus et esse.', 'diagnostico' => 'Saepe quia harum ducimus dolor illo.', 'notas_clinicas' => 'Animi et sequi at quidem accusantium nihil. Cupiditate totam est vel. Praesentium repellat fuga qui ipsa illo voluptatum quia neque. Vitae voluptatibus ipsam unde sint quis autem iusto.', 'examen' => null, 'fecha_tratamiento' => null, 'created_at' => '2026-03-26 09:05:46', 'updated_at' => '2026-03-26 09:05:46'],
    ['id' => 15, 'cita_id' => 53, 'doctor_id' => 22, 'paciente_id' => 101, 'motivo' => null, 'sintomas' => 'Asperiores aperiam qui quisquam voluptas eligendi.', 'diagnostico' => 'Perspiciatis rem quia tempore.', 'notas_clinicas' => 'Placeat perferendis doloribus velit doloremque ut accusamus sequi eveniet. Rem nemo rerum quos voluptatem consequatur vel.', 'examen' => null, 'fecha_tratamiento' => null, 'created_at' => '2026-03-26 09:05:46', 'updated_at' => '2026-03-26 09:05:46'],
    ['id' => 17, 'cita_id' => 1, 'doctor_id' => 1, 'paciente_id' => 12, 'motivo' => 'Dolor de estomago', 'sintomas' => 'Diarrea Dolor de pansa, calentura', 'diagnostico' => 'Sufre de indigestion', 'notas_clinicas' => 'Esta calienta', 'examen' => 'esta caliente', 'fecha_tratamiento' => null, 'created_at' => '2026-04-01 04:33:13', 'updated_at' => '2026-04-01 04:33:13'],
    ['id' => 19, 'cita_id' => 58, 'doctor_id' => 1, 'paciente_id' => 103, 'motivo' => 'seguimiento', 'sintomas' => 'dd', 'diagnostico' => 'dd', 'notas_clinicas' => 'dd', 'examen' => 'dd', 'fecha_tratamiento' => null, 'created_at' => '2026-04-01 05:10:54', 'updated_at' => '2026-04-01 05:10:54'],
    ['id' => 21, 'cita_id' => 55, 'doctor_id' => 1, 'paciente_id' => 1, 'motivo' => '1221', 'sintomas' => 'wqwqqw', 'diagnostico' => 'qwqw', 'notas_clinicas' => 'qwqw', 'examen' => 'qwq', 'fecha_tratamiento' => null, 'created_at' => '2026-04-01 05:14:07', 'updated_at' => '2026-04-01 05:14:07'],
    ['id' => 22, 'cita_id' => 57, 'doctor_id' => 1, 'paciente_id' => 104, 'motivo' => 'ddsdsss', 'sintomas' => 'ddsd', 'diagnostico' => 'sssdd', 'notas_clinicas' => 'sdd', 'examen' => 'sdds', 'fecha_tratamiento' => null, 'created_at' => '2026-04-01 05:33:49', 'updated_at' => '2026-04-01 05:33:49'],
    ['id' => 23, 'cita_id' => 61, 'doctor_id' => 1, 'paciente_id' => 104, 'motivo' => 'Seguimiento del corazon', 'sintomas' => 'Alta precion', 'diagnostico' => 'Tiene muy alta la frecuencia cardiaca', 'notas_clinicas' => 'Necesita reposo', 'examen' => 'Reposo', 'fecha_tratamiento' => null, 'created_at' => '2026-04-01 05:37:05', 'updated_at' => '2026-04-01 05:37:05'],
    ['id' => 24, 'cita_id' => 59, 'doctor_id' => 1, 'paciente_id' => 2, 'motivo' => 'Falta de sueño', 'sintomas' => 'sueño', 'diagnostico' => 'sueño', 'notas_clinicas' => 'sueño', 'examen' => 'sueño', 'fecha_tratamiento' => null, 'created_at' => '2026-04-01 05:53:16', 'updated_at' => '2026-04-01 05:53:16'],
    ['id' => 25, 'cita_id' => 62, 'doctor_id' => 1, 'paciente_id' => 104, 'motivo' => 'Nuvo de prueva', 'sintomas' => 'prueva', 'diagnostico' => 'ddd', 'notas_clinicas' => 'dd', 'examen' => 'ddd', 'fecha_tratamiento' => null, 'created_at' => '2026-04-01 10:13:15', 'updated_at' => '2026-04-01 10:13:15'],
    ['id' => 26, 'cita_id' => 68, 'doctor_id' => 1, 'paciente_id' => 2, 'motivo' => 'control', 'sintomas' => 'control', 'diagnostico' => 'control', 'notas_clinicas' => 'control', 'examen' => 'control', 'fecha_tratamiento' => null, 'created_at' => '2026-04-14 04:40:38', 'updated_at' => '2026-04-14 04:40:38'],
    ['id' => 27, 'cita_id' => 71, 'doctor_id' => 1, 'paciente_id' => 103, 'motivo' => 'control', 'sintomas' => 'control', 'diagnostico' => 'control', 'notas_clinicas' => 'control', 'examen' => 'control', 'fecha_tratamiento' => null, 'created_at' => '2026-04-14 05:01:13', 'updated_at' => '2026-04-14 05:01:13'],
    ['id' => 28, 'cita_id' => 74, 'doctor_id' => 1, 'paciente_id' => 103, 'motivo' => 'www', 'sintomas' => 'www', 'diagnostico' => 'ww', 'notas_clinicas' => 'ww', 'examen' => 'www', 'fecha_tratamiento' => null, 'created_at' => '2026-04-16 23:23:19', 'updated_at' => '2026-04-16 23:23:19'],
    ['id' => 29, 'cita_id' => 69, 'doctor_id' => 1, 'paciente_id' => 2, 'motivo' => '111', 'sintomas' => '111', 'diagnostico' => '11', 'notas_clinicas' => '11', 'examen' => '11', 'fecha_tratamiento' => null, 'created_at' => '2026-04-16 23:56:42', 'updated_at' => '2026-04-16 23:56:42'],
    ['id' => 30, 'cita_id' => 73, 'doctor_id' => 1, 'paciente_id' => 1, 'motivo' => 'www', 'sintomas' => 'www', 'diagnostico' => 'ww', 'notas_clinicas' => 'wwww', 'examen' => 'www', 'fecha_tratamiento' => null, 'created_at' => '2026-04-17 00:42:12', 'updated_at' => '2026-04-17 00:42:12'],
    ['id' => 31, 'cita_id' => 78, 'doctor_id' => 26, 'paciente_id' => 105, 'motivo' => 'Control del colon', 'sintomas' => 'Dolor estomacal y diarrea', 'diagnostico' => 'Necesita tomar mucha agua y control de alimentos', 'notas_clinicas' => 'no consumir alimentos grasosos', 'examen' => 'peso 55 kg', 'fecha_tratamiento' => null, 'created_at' => '2026-04-17 02:54:02', 'updated_at' => '2026-04-17 02:54:02'],
]);

    }
}
