<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MedicamentosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('medicamentos')->insert([
    ['id' => 1, 'nombre' => 'Paris Texas', 'sustancia_activa' => 'activa', 'concentracion' => '300', 'unidad' => 'ml', 'presentacion' => 'jarabe', 'cantidad_presentacion' => 230, 'requiere_receta' => 1, 'descripcion_general' => 'dcsdcsdcsd', 'imagen_url' => 'medicamento-1.png', 'categoria_id' => 2],
    ['id' => 2, 'nombre' => 'Paris Texas', 'sustancia_activa' => 'activa', 'concentracion' => '300', 'unidad' => 'ml', 'presentacion' => 'jarabe', 'cantidad_presentacion' => 230, 'requiere_receta' => 1, 'descripcion_general' => 'dcsdcsdcsd', 'imagen_url' => 'medicamento-2.png', 'categoria_id' => 2],
    ['id' => 4, 'nombre' => 'Amoxicilina 250mg', 'sustancia_activa' => 'ducimus', 'concentracion' => '250', 'unidad' => 'mg', 'presentacion' => 'Jarabe', 'cantidad_presentacion' => 11, 'requiere_receta' => 1, 'descripcion_general' => 'Mollitia itaque atque tenetur occaecati eveniet voluptatibus.', 'imagen_url' => null, 'categoria_id' => null],
    ['id' => 5, 'nombre' => 'Amoxicilina 250mg', 'sustancia_activa' => 'reiciendis', 'concentracion' => '250', 'unidad' => 'mg', 'presentacion' => 'Jarabe', 'cantidad_presentacion' => 25, 'requiere_receta' => 0, 'descripcion_general' => 'Voluptatem voluptas quod incidunt corporis quia tenetur qui.', 'imagen_url' => null, 'categoria_id' => null],
    ['id' => 6, 'nombre' => 'Amoxicilina 100mg', 'sustancia_activa' => 'nulla', 'concentracion' => '250', 'unidad' => 'mg', 'presentacion' => 'Cápsulas', 'cantidad_presentacion' => 11, 'requiere_receta' => 0, 'descripcion_general' => 'Officia voluptate et fugiat fugiat.', 'imagen_url' => null, 'categoria_id' => null],
    ['id' => 7, 'nombre' => 'Aspirina 500mg', 'sustancia_activa' => 'assumenda', 'concentracion' => '100', 'unidad' => 'mg', 'presentacion' => 'Cápsulas', 'cantidad_presentacion' => 15, 'requiere_receta' => 0, 'descripcion_general' => 'Placeat qui vel fugit aut porro et ullam.', 'imagen_url' => null, 'categoria_id' => null],
    ['id' => 8, 'nombre' => 'Aspirina 250mg', 'sustancia_activa' => 'dolorem', 'concentracion' => '100', 'unidad' => 'mg', 'presentacion' => 'Cápsulas', 'cantidad_presentacion' => 22, 'requiere_receta' => 1, 'descripcion_general' => 'Molestiae et aspernatur est ut magnam accusantium illum omnis.', 'imagen_url' => null, 'categoria_id' => null],
    ['id' => 9, 'nombre' => 'Amoxicilina 100mg', 'sustancia_activa' => 'itaque', 'concentracion' => '100', 'unidad' => 'mg', 'presentacion' => 'Cápsulas', 'cantidad_presentacion' => 22, 'requiere_receta' => 1, 'descripcion_general' => 'Odit sint consequatur sit aliquid atque aut qui aut.', 'imagen_url' => null, 'categoria_id' => null],
    ['id' => 10, 'nombre' => 'Loratadina 250mg', 'sustancia_activa' => 'delectus', 'concentracion' => '250', 'unidad' => 'mg', 'presentacion' => 'Jarabe', 'cantidad_presentacion' => 12, 'requiere_receta' => 1, 'descripcion_general' => 'Enim voluptas veritatis atque doloremque quis.', 'imagen_url' => null, 'categoria_id' => null],
    ['id' => 11, 'nombre' => 'Amoxicilina 500mg', 'sustancia_activa' => 'consequatur', 'concentracion' => '500', 'unidad' => 'mg', 'presentacion' => 'Tabletas', 'cantidad_presentacion' => 30, 'requiere_receta' => 1, 'descripcion_general' => 'Nihil ea similique reprehenderit.', 'imagen_url' => null, 'categoria_id' => null],
    ['id' => 12, 'nombre' => 'Paracetamol 100mg', 'sustancia_activa' => 'est', 'concentracion' => '250', 'unidad' => 'mg', 'presentacion' => 'Jarabe', 'cantidad_presentacion' => 26, 'requiere_receta' => 1, 'descripcion_general' => 'Voluptates corporis vitae iste voluptas ipsum fugiat debitis quia.', 'imagen_url' => null, 'categoria_id' => null],
    ['id' => 13, 'nombre' => 'Aspirina 500mg', 'sustancia_activa' => 'quia', 'concentracion' => '500', 'unidad' => 'mg', 'presentacion' => 'Tabletas', 'cantidad_presentacion' => 17, 'requiere_receta' => 0, 'descripcion_general' => 'Id aspernatur autem vel explicabo non voluptatem nam.', 'imagen_url' => null, 'categoria_id' => null],
    ['id' => 14, 'nombre' => 'Amoxicilina 500mg', 'sustancia_activa' => 'amet', 'concentracion' => '100', 'unidad' => 'mg', 'presentacion' => 'Jarabe', 'cantidad_presentacion' => 19, 'requiere_receta' => 1, 'descripcion_general' => 'Quo quia ut quod veritatis dicta.', 'imagen_url' => null, 'categoria_id' => null],
    ['id' => 15, 'nombre' => 'Omeprazol 100mg', 'sustancia_activa' => 'doloremque', 'concentracion' => '500', 'unidad' => 'mg', 'presentacion' => 'Tabletas', 'cantidad_presentacion' => 30, 'requiere_receta' => 0, 'descripcion_general' => 'Iste provident veritatis dolorem recusandae vel inventore.', 'imagen_url' => null, 'categoria_id' => null],
    ['id' => 16, 'nombre' => 'Loratadina 100mg', 'sustancia_activa' => 'non', 'concentracion' => '100', 'unidad' => 'mg', 'presentacion' => 'Cápsulas', 'cantidad_presentacion' => 21, 'requiere_receta' => 0, 'descripcion_general' => 'Nisi non nam eius perferendis.', 'imagen_url' => null, 'categoria_id' => null],
    ['id' => 17, 'nombre' => 'Aspirina 250mg', 'sustancia_activa' => 'nobis', 'concentracion' => '500', 'unidad' => 'mg', 'presentacion' => 'Cápsulas', 'cantidad_presentacion' => 27, 'requiere_receta' => 1, 'descripcion_general' => 'Veritatis sequi cumque explicabo.', 'imagen_url' => null, 'categoria_id' => null],
    ['id' => 18, 'nombre' => 'Amoxicilina 500mg', 'sustancia_activa' => 'repellat', 'concentracion' => '250', 'unidad' => 'mg', 'presentacion' => 'Tabletas', 'cantidad_presentacion' => 18, 'requiere_receta' => 1, 'descripcion_general' => 'Quisquam laudantium voluptas deserunt.', 'imagen_url' => null, 'categoria_id' => null],
    ['id' => 19, 'nombre' => 'Omeprazol 250mg', 'sustancia_activa' => 'quia', 'concentracion' => '250', 'unidad' => 'mg', 'presentacion' => 'Cápsulas', 'cantidad_presentacion' => 17, 'requiere_receta' => 1, 'descripcion_general' => 'Velit eaque non corporis eaque repudiandae quia.', 'imagen_url' => null, 'categoria_id' => null],
    ['id' => 20, 'nombre' => 'Amoxicilina 100mg', 'sustancia_activa' => 'quas', 'concentracion' => '100', 'unidad' => 'mg', 'presentacion' => 'Tabletas', 'cantidad_presentacion' => 11, 'requiere_receta' => 1, 'descripcion_general' => 'Aut iste est et quia reprehenderit tempora.', 'imagen_url' => null, 'categoria_id' => null],
    ['id' => 21, 'nombre' => 'Loratadina 100mg', 'sustancia_activa' => 'maxime', 'concentracion' => '250', 'unidad' => 'mg', 'presentacion' => 'Cápsulas', 'cantidad_presentacion' => 25, 'requiere_receta' => 0, 'descripcion_general' => 'Enim est soluta explicabo minus sed.', 'imagen_url' => null, 'categoria_id' => null],
    ['id' => 22, 'nombre' => 'Ibuprofeno 500mg', 'sustancia_activa' => 'blanditiis', 'concentracion' => '500', 'unidad' => 'mg', 'presentacion' => 'Tabletas', 'cantidad_presentacion' => 28, 'requiere_receta' => 0, 'descripcion_general' => 'Aut adipisci asperiores autem labore eius.', 'imagen_url' => null, 'categoria_id' => null],
    ['id' => 23, 'nombre' => 'Omeprazol 100mg', 'sustancia_activa' => 'cum', 'concentracion' => '500', 'unidad' => 'mg', 'presentacion' => 'Tabletas', 'cantidad_presentacion' => 16, 'requiere_receta' => 1, 'descripcion_general' => 'Quas laborum rerum et repudiandae consequuntur.', 'imagen_url' => null, 'categoria_id' => null],
    ['id' => 24, 'nombre' => 'Omeprazol 250mg', 'sustancia_activa' => 'veniam', 'concentracion' => '100', 'unidad' => 'mg', 'presentacion' => 'Tabletas', 'cantidad_presentacion' => 13, 'requiere_receta' => 0, 'descripcion_general' => 'Quaerat consectetur et aliquam hic quis omnis veniam.', 'imagen_url' => null, 'categoria_id' => null],
    ['id' => 25, 'nombre' => 'Ibuprofeno 500mg', 'sustancia_activa' => 'et', 'concentracion' => '500', 'unidad' => 'mg', 'presentacion' => 'Tabletas', 'cantidad_presentacion' => 25, 'requiere_receta' => 1, 'descripcion_general' => 'Dolorum sit nulla ut nesciunt.', 'imagen_url' => null, 'categoria_id' => null],
    ['id' => 26, 'nombre' => 'Amoxicilina 100mg', 'sustancia_activa' => 'sunt', 'concentracion' => '500', 'unidad' => 'mg', 'presentacion' => 'Tabletas', 'cantidad_presentacion' => 27, 'requiere_receta' => 0, 'descripcion_general' => 'In aut delectus qui et doloremque earum ex.', 'imagen_url' => null, 'categoria_id' => null],
    ['id' => 27, 'nombre' => 'Amoxicilina 500mg', 'sustancia_activa' => 'mollitia', 'concentracion' => '500', 'unidad' => 'mg', 'presentacion' => 'Jarabe', 'cantidad_presentacion' => 11, 'requiere_receta' => 1, 'descripcion_general' => 'Veniam in et veritatis minus nihil aut consequatur.', 'imagen_url' => null, 'categoria_id' => null],
    ['id' => 28, 'nombre' => 'Ibuprofeno 100mg', 'sustancia_activa' => 'minima', 'concentracion' => '500', 'unidad' => 'mg', 'presentacion' => 'Cápsulas', 'cantidad_presentacion' => 30, 'requiere_receta' => 1, 'descripcion_general' => 'Inventore laudantium numquam vitae voluptatem possimus.', 'imagen_url' => null, 'categoria_id' => null],
    ['id' => 29, 'nombre' => 'Omeprazol 100mg', 'sustancia_activa' => 'nostrum', 'concentracion' => '500', 'unidad' => 'mg', 'presentacion' => 'Jarabe', 'cantidad_presentacion' => 29, 'requiere_receta' => 1, 'descripcion_general' => 'Quo ullam incidunt impedit sunt dolores.', 'imagen_url' => null, 'categoria_id' => null],
    ['id' => 30, 'nombre' => 'Paracetamol 100mg', 'sustancia_activa' => 'voluptas', 'concentracion' => '100', 'unidad' => 'mg', 'presentacion' => 'Tabletas', 'cantidad_presentacion' => 27, 'requiere_receta' => 1, 'descripcion_general' => 'Atque et atque consectetur minima enim magnam distinctio mollitia.', 'imagen_url' => null, 'categoria_id' => null],
    ['id' => 31, 'nombre' => 'Paracetamol 250mg', 'sustancia_activa' => 'quo', 'concentracion' => '100', 'unidad' => 'mg', 'presentacion' => 'Jarabe', 'cantidad_presentacion' => 14, 'requiere_receta' => 0, 'descripcion_general' => 'Et occaecati sed amet incidunt architecto dolores.', 'imagen_url' => null, 'categoria_id' => null],
    ['id' => 32, 'nombre' => 'Aspirina 100mg', 'sustancia_activa' => 'debitis', 'concentracion' => '500', 'unidad' => 'mg', 'presentacion' => 'Cápsulas', 'cantidad_presentacion' => 18, 'requiere_receta' => 1, 'descripcion_general' => 'Et cum minima expedita impedit.', 'imagen_url' => null, 'categoria_id' => null],
    ['id' => 33, 'nombre' => 'Amoxicilina 500mg', 'sustancia_activa' => 'libero', 'concentracion' => '500', 'unidad' => 'mg', 'presentacion' => 'Jarabe', 'cantidad_presentacion' => 24, 'requiere_receta' => 1, 'descripcion_general' => 'Facilis aliquid sed est.', 'imagen_url' => null, 'categoria_id' => null],
    ['id' => 34, 'nombre' => 'Loratadina 250mg', 'sustancia_activa' => 'eius', 'concentracion' => '500', 'unidad' => 'mg', 'presentacion' => 'Jarabe', 'cantidad_presentacion' => 20, 'requiere_receta' => 1, 'descripcion_general' => 'Omnis porro est aspernatur distinctio quod qui.', 'imagen_url' => null, 'categoria_id' => null],
    ['id' => 35, 'nombre' => 'Aspirina 100mg', 'sustancia_activa' => 'neque', 'concentracion' => '100', 'unidad' => 'mg', 'presentacion' => 'Jarabe', 'cantidad_presentacion' => 29, 'requiere_receta' => 1, 'descripcion_general' => 'Quasi adipisci magnam nisi laborum eveniet quia hic maxime.', 'imagen_url' => null, 'categoria_id' => null],
    ['id' => 36, 'nombre' => 'Aspirina 250mg', 'sustancia_activa' => 'commodi', 'concentracion' => '100', 'unidad' => 'mg', 'presentacion' => 'Jarabe', 'cantidad_presentacion' => 10, 'requiere_receta' => 0, 'descripcion_general' => 'Consequuntur architecto quia aut repellendus amet rerum.', 'imagen_url' => null, 'categoria_id' => null],
    ['id' => 37, 'nombre' => 'Amoxicilina 250mg', 'sustancia_activa' => 'harum', 'concentracion' => '100', 'unidad' => 'mg', 'presentacion' => 'Jarabe', 'cantidad_presentacion' => 20, 'requiere_receta' => 0, 'descripcion_general' => 'Consequuntur quo dolorem praesentium et.', 'imagen_url' => null, 'categoria_id' => null],
    ['id' => 38, 'nombre' => 'Amoxicilina 500mg', 'sustancia_activa' => 'assumenda', 'concentracion' => '100', 'unidad' => 'mg', 'presentacion' => 'Tabletas', 'cantidad_presentacion' => 23, 'requiere_receta' => 0, 'descripcion_general' => 'Ea est ex eum dicta quas ut rem.', 'imagen_url' => null, 'categoria_id' => null],
    ['id' => 39, 'nombre' => 'Loratadina 250mg', 'sustancia_activa' => 'quod', 'concentracion' => '250', 'unidad' => 'mg', 'presentacion' => 'Jarabe', 'cantidad_presentacion' => 13, 'requiere_receta' => 0, 'descripcion_general' => 'Quia non sed ut odio veritatis iusto quia.', 'imagen_url' => null, 'categoria_id' => null],
    ['id' => 40, 'nombre' => 'Aspirina 250mg', 'sustancia_activa' => 'fugit', 'concentracion' => '250', 'unidad' => 'mg', 'presentacion' => 'Jarabe', 'cantidad_presentacion' => 22, 'requiere_receta' => 1, 'descripcion_general' => 'Est fugiat quas totam cum provident.', 'imagen_url' => null, 'categoria_id' => null],
    ['id' => 41, 'nombre' => 'Paracetamol 100mg', 'sustancia_activa' => 'itaque', 'concentracion' => '100', 'unidad' => 'mg', 'presentacion' => 'Tabletas', 'cantidad_presentacion' => 26, 'requiere_receta' => 0, 'descripcion_general' => 'Error consequatur aut et inventore.', 'imagen_url' => null, 'categoria_id' => null],
    ['id' => 42, 'nombre' => 'Aspirina 250mg', 'sustancia_activa' => 'aperiam', 'concentracion' => '500', 'unidad' => 'mg', 'presentacion' => 'Cápsulas', 'cantidad_presentacion' => 26, 'requiere_receta' => 1, 'descripcion_general' => 'Maiores nostrum eaque sint dolorem animi nemo ut quod.', 'imagen_url' => null, 'categoria_id' => null],
    ['id' => 43, 'nombre' => 'Ibuprofeno 500mg', 'sustancia_activa' => 'iure', 'concentracion' => '500', 'unidad' => 'mg', 'presentacion' => 'Cápsulas', 'cantidad_presentacion' => 23, 'requiere_receta' => 0, 'descripcion_general' => 'Rerum molestias voluptatem qui distinctio consequuntur sit ut.', 'imagen_url' => null, 'categoria_id' => null],
    ['id' => 44, 'nombre' => 'Paracetamol 500mg', 'sustancia_activa' => 'aut', 'concentracion' => '250', 'unidad' => 'mg', 'presentacion' => 'Jarabe', 'cantidad_presentacion' => 22, 'requiere_receta' => 0, 'descripcion_general' => 'Dolorem tempora aut repudiandae voluptate qui corrupti.', 'imagen_url' => null, 'categoria_id' => null],
    ['id' => 45, 'nombre' => 'Paracetamol 250mg', 'sustancia_activa' => 'est', 'concentracion' => '250', 'unidad' => 'mg', 'presentacion' => 'Tabletas', 'cantidad_presentacion' => 28, 'requiere_receta' => 0, 'descripcion_general' => 'Atque reiciendis et blanditiis aliquam.', 'imagen_url' => null, 'categoria_id' => null],
    ['id' => 46, 'nombre' => 'Loratadina 500mg', 'sustancia_activa' => 'aut', 'concentracion' => '250', 'unidad' => 'mg', 'presentacion' => 'Jarabe', 'cantidad_presentacion' => 26, 'requiere_receta' => 0, 'descripcion_general' => 'Et optio sunt labore illum repellendus rerum quasi nemo.', 'imagen_url' => null, 'categoria_id' => null],
    ['id' => 47, 'nombre' => 'Paracetamol 500mg', 'sustancia_activa' => 'placeat', 'concentracion' => '100', 'unidad' => 'mg', 'presentacion' => 'Tabletas', 'cantidad_presentacion' => 23, 'requiere_receta' => 0, 'descripcion_general' => 'Fugiat placeat ipsam consequatur et omnis suscipit debitis.', 'imagen_url' => null, 'categoria_id' => null],
    ['id' => 48, 'nombre' => 'Loratadina 250mg', 'sustancia_activa' => 'ex', 'concentracion' => '100', 'unidad' => 'mg', 'presentacion' => 'Jarabe', 'cantidad_presentacion' => 16, 'requiere_receta' => 0, 'descripcion_general' => 'Dolores sit voluptatem quae animi dolor porro sunt nihil.', 'imagen_url' => null, 'categoria_id' => null],
    ['id' => 49, 'nombre' => 'Aspirina 100mg', 'sustancia_activa' => 'eligendi', 'concentracion' => '500', 'unidad' => 'mg', 'presentacion' => 'Jarabe', 'cantidad_presentacion' => 20, 'requiere_receta' => 1, 'descripcion_general' => 'Omnis quidem qui molestiae quia.', 'imagen_url' => null, 'categoria_id' => null],
    ['id' => 50, 'nombre' => 'Ibuprofeno 500mg', 'sustancia_activa' => 'amet', 'concentracion' => '500', 'unidad' => 'mg', 'presentacion' => 'Cápsulas', 'cantidad_presentacion' => 19, 'requiere_receta' => 0, 'descripcion_general' => 'Quaerat et quas omnis cum quidem fugit voluptate rerum.', 'imagen_url' => null, 'categoria_id' => null],
    ['id' => 51, 'nombre' => 'Ibuprofeno 250mg', 'sustancia_activa' => 'sint', 'concentracion' => '100', 'unidad' => 'mg', 'presentacion' => 'Tabletas', 'cantidad_presentacion' => 20, 'requiere_receta' => 1, 'descripcion_general' => 'Vel at voluptatem animi provident pariatur nesciunt quia.', 'imagen_url' => null, 'categoria_id' => null],
    ['id' => 52, 'nombre' => 'Omeprazol 100mg', 'sustancia_activa' => 'iusto', 'concentracion' => '500', 'unidad' => 'mg', 'presentacion' => 'Cápsulas', 'cantidad_presentacion' => 20, 'requiere_receta' => 0, 'descripcion_general' => 'Possimus id corrupti laudantium aut iure corporis.', 'imagen_url' => null, 'categoria_id' => null],
    ['id' => 53, 'nombre' => 'Amoxicilina 500mg', 'sustancia_activa' => 'illo', 'concentracion' => '250', 'unidad' => 'mg', 'presentacion' => 'Cápsulas', 'cantidad_presentacion' => 13, 'requiere_receta' => 1, 'descripcion_general' => 'Non quis ut consequatur.', 'imagen_url' => null, 'categoria_id' => null],
    ['id' => 54, 'nombre' => 'Ibuprofeno 500mg', 'sustancia_activa' => 'atque', 'concentracion' => '500', 'unidad' => 'mg', 'presentacion' => 'Cápsulas', 'cantidad_presentacion' => 13, 'requiere_receta' => 1, 'descripcion_general' => 'Aliquam quo reiciendis quia molestiae.', 'imagen_url' => null, 'categoria_id' => null],
    ['id' => 55, 'nombre' => 'Ibuprofeno 250mg', 'sustancia_activa' => 'voluptatem', 'concentracion' => '500', 'unidad' => 'mg', 'presentacion' => 'Cápsulas', 'cantidad_presentacion' => 25, 'requiere_receta' => 1, 'descripcion_general' => 'Aut et magnam laboriosam saepe animi molestiae enim.', 'imagen_url' => null, 'categoria_id' => null],
    ['id' => 56, 'nombre' => 'Omeprazol 100mg', 'sustancia_activa' => 'rerum', 'concentracion' => '500', 'unidad' => 'mg', 'presentacion' => 'Jarabe', 'cantidad_presentacion' => 25, 'requiere_receta' => 0, 'descripcion_general' => 'Velit tempore porro quo aspernatur qui velit adipisci.', 'imagen_url' => null, 'categoria_id' => null],
    ['id' => 57, 'nombre' => 'Paracetamol 500mg', 'sustancia_activa' => 'vel', 'concentracion' => '100', 'unidad' => 'mg', 'presentacion' => 'Jarabe', 'cantidad_presentacion' => 11, 'requiere_receta' => 1, 'descripcion_general' => 'Omnis odio consequatur ut maxime molestias veritatis sit ab.', 'imagen_url' => null, 'categoria_id' => null],
    ['id' => 58, 'nombre' => 'Amoxicilina 500mg', 'sustancia_activa' => 'doloremque', 'concentracion' => '500', 'unidad' => 'mg', 'presentacion' => 'Jarabe', 'cantidad_presentacion' => 19, 'requiere_receta' => 1, 'descripcion_general' => 'Et id at assumenda illo corrupti voluptas quam ea.', 'imagen_url' => null, 'categoria_id' => null],
    ['id' => 59, 'nombre' => 'Paracetamol 250mg', 'sustancia_activa' => 'consectetur', 'concentracion' => '250', 'unidad' => 'mg', 'presentacion' => 'Jarabe', 'cantidad_presentacion' => 19, 'requiere_receta' => 1, 'descripcion_general' => 'Ratione facere quod quo neque aperiam soluta.', 'imagen_url' => null, 'categoria_id' => null],
    ['id' => 60, 'nombre' => 'Omeprazol 500mg', 'sustancia_activa' => 'tempore', 'concentracion' => '250', 'unidad' => 'mg', 'presentacion' => 'Cápsulas', 'cantidad_presentacion' => 18, 'requiere_receta' => 1, 'descripcion_general' => 'Aut reprehenderit labore deserunt consequuntur ipsum vero culpa voluptatem.', 'imagen_url' => null, 'categoria_id' => null],
    ['id' => 61, 'nombre' => 'Loratadina 500mg', 'sustancia_activa' => 'reiciendis', 'concentracion' => '500', 'unidad' => 'mg', 'presentacion' => 'Jarabe', 'cantidad_presentacion' => 11, 'requiere_receta' => 1, 'descripcion_general' => 'Dolorem saepe similique et distinctio et et.', 'imagen_url' => null, 'categoria_id' => null],
    ['id' => 62, 'nombre' => 'Amoxicilina 250mg', 'sustancia_activa' => 'amet', 'concentracion' => '500', 'unidad' => 'mg', 'presentacion' => 'Tabletas', 'cantidad_presentacion' => 26, 'requiere_receta' => 1, 'descripcion_general' => 'Placeat molestiae cupiditate voluptatum animi.', 'imagen_url' => null, 'categoria_id' => null],
    ['id' => 63, 'nombre' => 'Loratadina 100mg', 'sustancia_activa' => 'et', 'concentracion' => '100', 'unidad' => 'mg', 'presentacion' => 'Jarabe', 'cantidad_presentacion' => 26, 'requiere_receta' => 0, 'descripcion_general' => 'Nisi nesciunt vitae est voluptates.', 'imagen_url' => null, 'categoria_id' => null],
    ['id' => 64, 'nombre' => 'Loratadina 250mg', 'sustancia_activa' => 'culpa', 'concentracion' => '100', 'unidad' => 'mg', 'presentacion' => 'Tabletas', 'cantidad_presentacion' => 13, 'requiere_receta' => 0, 'descripcion_general' => 'Sit eos delectus temporibus molestias aut voluptas.', 'imagen_url' => null, 'categoria_id' => null],
]);

    }
}
