<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RecetaDetalleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('receta_detalle')->insert([
    ['id' => 1, 'receta_id' => 1, 'medicamento_id' => 23, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '10 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-03-25 09:43:16'],
    ['id' => 2, 'receta_id' => 2, 'medicamento_id' => 18, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '7 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-03-25 09:43:16'],
    ['id' => 3, 'receta_id' => 3, 'medicamento_id' => 26, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '9 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-03-25 09:43:16'],
    ['id' => 4, 'receta_id' => 3, 'medicamento_id' => 14, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '4 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-03-25 09:43:16'],
    ['id' => 5, 'receta_id' => 4, 'medicamento_id' => 29, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '6 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-03-25 09:43:16'],
    ['id' => 6, 'receta_id' => 4, 'medicamento_id' => 11, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '3 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-03-25 09:43:16'],
    ['id' => 7, 'receta_id' => 4, 'medicamento_id' => 29, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '10 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-03-25 09:43:16'],
    ['id' => 8, 'receta_id' => 5, 'medicamento_id' => 29, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '10 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-03-25 09:43:16'],
    ['id' => 9, 'receta_id' => 6, 'medicamento_id' => 24, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '8 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-03-25 09:43:16'],
    ['id' => 10, 'receta_id' => 6, 'medicamento_id' => 14, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '9 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-03-25 09:43:16'],
    ['id' => 11, 'receta_id' => 7, 'medicamento_id' => 30, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '9 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-03-25 09:43:16'],
    ['id' => 12, 'receta_id' => 7, 'medicamento_id' => 10, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '7 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-03-25 09:43:16'],
    ['id' => 13, 'receta_id' => 8, 'medicamento_id' => 11, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '4 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-03-25 09:43:16'],
    ['id' => 14, 'receta_id' => 8, 'medicamento_id' => 18, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '3 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-03-25 09:43:16'],
    ['id' => 15, 'receta_id' => 9, 'medicamento_id' => 16, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '6 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-03-25 09:43:16'],
    ['id' => 16, 'receta_id' => 9, 'medicamento_id' => 29, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '4 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-03-25 09:43:16'],
    ['id' => 17, 'receta_id' => 10, 'medicamento_id' => 15, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '9 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-03-25 09:43:16'],
    ['id' => 18, 'receta_id' => 11, 'medicamento_id' => 11, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '6 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-03-25 09:43:16'],
    ['id' => 19, 'receta_id' => 11, 'medicamento_id' => 27, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '6 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-03-25 09:43:16'],
    ['id' => 20, 'receta_id' => 12, 'medicamento_id' => 21, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '10 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-03-25 09:43:16'],
    ['id' => 21, 'receta_id' => 13, 'medicamento_id' => 12, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '6 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-03-25 09:43:16'],
    ['id' => 22, 'receta_id' => 14, 'medicamento_id' => 12, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '8 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-03-25 09:43:16'],
    ['id' => 23, 'receta_id' => 14, 'medicamento_id' => 27, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '9 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-03-25 09:43:16'],
    ['id' => 24, 'receta_id' => 15, 'medicamento_id' => 20, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '4 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-03-25 09:43:16'],
    ['id' => 25, 'receta_id' => 15, 'medicamento_id' => 22, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '3 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-03-25 09:43:16'],
    ['id' => 26, 'receta_id' => 15, 'medicamento_id' => 11, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '4 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-03-25 09:43:16'],
    ['id' => 27, 'receta_id' => 16, 'medicamento_id' => 2, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '7 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-01-09 09:43:16'],
    ['id' => 28, 'receta_id' => 17, 'medicamento_id' => 19, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '9 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-03-04 09:43:16'],
    ['id' => 29, 'receta_id' => 17, 'medicamento_id' => 26, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '6 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-03-04 09:43:16'],
    ['id' => 30, 'receta_id' => 18, 'medicamento_id' => 31, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '5 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-02-23 09:43:16'],
    ['id' => 31, 'receta_id' => 18, 'medicamento_id' => 20, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '7 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-02-23 09:43:16'],
    ['id' => 32, 'receta_id' => 19, 'medicamento_id' => 16, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '6 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-01-19 09:43:16'],
    ['id' => 33, 'receta_id' => 19, 'medicamento_id' => 24, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '10 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-01-19 09:43:16'],
    ['id' => 34, 'receta_id' => 20, 'medicamento_id' => 28, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '10 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-01-20 09:43:16'],
    ['id' => 35, 'receta_id' => 20, 'medicamento_id' => 8, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '10 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-01-20 09:43:16'],
    ['id' => 36, 'receta_id' => 20, 'medicamento_id' => 17, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '6 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-01-20 09:43:16'],
    ['id' => 37, 'receta_id' => 21, 'medicamento_id' => 19, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '5 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-01-23 09:43:16'],
    ['id' => 38, 'receta_id' => 22, 'medicamento_id' => 33, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '5 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-03-03 09:43:16'],
    ['id' => 39, 'receta_id' => 22, 'medicamento_id' => 2, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '10 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-03-03 09:43:16'],
    ['id' => 40, 'receta_id' => 23, 'medicamento_id' => 29, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '9 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2025-12-29 09:43:16'],
    ['id' => 41, 'receta_id' => 23, 'medicamento_id' => 24, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '8 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2025-12-29 09:43:16'],
    ['id' => 42, 'receta_id' => 24, 'medicamento_id' => 24, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '7 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-03-20 09:43:16'],
    ['id' => 43, 'receta_id' => 24, 'medicamento_id' => 10, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '9 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-03-20 09:43:16'],
    ['id' => 44, 'receta_id' => 25, 'medicamento_id' => 24, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '10 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-02-23 09:43:16'],
    ['id' => 45, 'receta_id' => 26, 'medicamento_id' => 23, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '8 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-02-19 09:43:16'],
    ['id' => 46, 'receta_id' => 26, 'medicamento_id' => 11, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '3 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-02-19 09:43:16'],
    ['id' => 47, 'receta_id' => 26, 'medicamento_id' => 2, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '9 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-02-19 09:43:16'],
    ['id' => 48, 'receta_id' => 27, 'medicamento_id' => 12, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '6 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-02-04 09:43:16'],
    ['id' => 49, 'receta_id' => 27, 'medicamento_id' => 17, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '10 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-02-04 09:43:16'],
    ['id' => 50, 'receta_id' => 28, 'medicamento_id' => 23, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '6 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2025-12-28 09:43:16'],
    ['id' => 51, 'receta_id' => 28, 'medicamento_id' => 28, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '8 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2025-12-28 09:43:16'],
    ['id' => 52, 'receta_id' => 29, 'medicamento_id' => 15, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '8 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-01-13 09:43:16'],
    ['id' => 53, 'receta_id' => 30, 'medicamento_id' => 19, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '4 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-02-11 09:43:16'],
    ['id' => 54, 'receta_id' => 31, 'medicamento_id' => 9, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '9 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-01-05 09:43:16'],
    ['id' => 55, 'receta_id' => 31, 'medicamento_id' => 11, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '6 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-01-05 09:43:16'],
    ['id' => 56, 'receta_id' => 31, 'medicamento_id' => 27, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '9 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-01-05 09:43:16'],
    ['id' => 57, 'receta_id' => 32, 'medicamento_id' => 15, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '3 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-02-01 09:43:16'],
    ['id' => 58, 'receta_id' => 32, 'medicamento_id' => 15, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '3 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-02-01 09:43:16'],
    ['id' => 59, 'receta_id' => 33, 'medicamento_id' => 21, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '4 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-02-21 09:43:16'],
    ['id' => 60, 'receta_id' => 33, 'medicamento_id' => 26, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '5 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-02-21 09:43:16'],
    ['id' => 61, 'receta_id' => 34, 'medicamento_id' => 23, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '7 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-02-06 09:43:16'],
    ['id' => 62, 'receta_id' => 34, 'medicamento_id' => 8, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '3 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-02-06 09:43:16'],
    ['id' => 63, 'receta_id' => 34, 'medicamento_id' => 28, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '9 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-02-06 09:43:16'],
    ['id' => 64, 'receta_id' => 35, 'medicamento_id' => 25, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '4 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-03-04 09:43:16'],
    ['id' => 65, 'receta_id' => 35, 'medicamento_id' => 26, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '5 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-03-04 09:43:16'],
    ['id' => 66, 'receta_id' => 36, 'medicamento_id' => 24, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '7 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-03-16 09:43:16'],
    ['id' => 67, 'receta_id' => 36, 'medicamento_id' => 7, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '8 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-03-16 09:43:16'],
    ['id' => 68, 'receta_id' => 37, 'medicamento_id' => 29, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '7 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2025-12-26 09:43:16'],
    ['id' => 69, 'receta_id' => 37, 'medicamento_id' => 19, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '6 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2025-12-26 09:43:16'],
    ['id' => 70, 'receta_id' => 38, 'medicamento_id' => 32, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '8 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-01-05 09:43:16'],
    ['id' => 71, 'receta_id' => 38, 'medicamento_id' => 8, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '10 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-01-05 09:43:16'],
    ['id' => 72, 'receta_id' => 39, 'medicamento_id' => 22, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '6 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-01-25 09:43:16'],
    ['id' => 73, 'receta_id' => 39, 'medicamento_id' => 23, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '6 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-01-25 09:43:16'],
    ['id' => 74, 'receta_id' => 39, 'medicamento_id' => 20, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '8 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2026-01-25 09:43:16'],
    ['id' => 75, 'receta_id' => 40, 'medicamento_id' => 31, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '10 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2025-12-31 09:43:16'],
    ['id' => 76, 'receta_id' => 40, 'medicamento_id' => 17, 'dosis' => '1 tableta', 'frecuencia' => 'Cada 8 horas', 'duracion' => '5 días', 'instrucciones' => 'Tomar con alimentos', 'creado_en' => '2025-12-31 09:43:16'],
    ['id' => 77, 'receta_id' => 41, 'medicamento_id' => 14, 'dosis' => '1 tableta', 'frecuencia' => 'cada 8h', 'duracion' => '3 dias', 'instrucciones' => 'Tomar cada 3 horas una tableta durante 3 dias', 'creado_en' => null],
    ['id' => 78, 'receta_id' => 41, 'medicamento_id' => 2, 'dosis' => '1 tableta', 'frecuencia' => '12 horas', 'duracion' => '7 dias', 'instrucciones' => 'Tomarlo con cuidado', 'creado_en' => null],
    ['id' => 79, 'receta_id' => 42, 'medicamento_id' => 1, 'dosis' => '2', 'frecuencia' => '23', 'duracion' => '23', 'instrucciones' => '23333', 'creado_en' => null],
    ['id' => 80, 'receta_id' => 43, 'medicamento_id' => 6, 'dosis' => '11', 'frecuencia' => '11', 'duracion' => '11', 'instrucciones' => '11', 'creado_en' => null],
    ['id' => 81, 'receta_id' => 45, 'medicamento_id' => 7, 'dosis' => '12', 'frecuencia' => '12', 'duracion' => '12', 'instrucciones' => '12', 'creado_en' => null],
    ['id' => 82, 'receta_id' => 45, 'medicamento_id' => 10, 'dosis' => '12', 'frecuencia' => '12', 'duracion' => '12', 'instrucciones' => '12', 'creado_en' => null],
    ['id' => 83, 'receta_id' => 46, 'medicamento_id' => 55, 'dosis' => '2 horas', 'frecuencia' => '12 horas', 'duracion' => '5 dias', 'instrucciones' => 'tomar cada 5 dias', 'creado_en' => null],
    ['id' => 84, 'receta_id' => 46, 'medicamento_id' => 11, 'dosis' => '20 ml', 'frecuencia' => 'cada 8 horas', 'duracion' => '5 dias', 'instrucciones' => 'Tomar el medicamento cada 8 horas por 5 dias', 'creado_en' => null],
    ['id' => 85, 'receta_id' => 47, 'medicamento_id' => 5, 'dosis' => '2', 'frecuencia' => '2', 'duracion' => '2', 'instrucciones' => '2', 'creado_en' => null],
    ['id' => 86, 'receta_id' => 48, 'medicamento_id' => 32, 'dosis' => '2 tabletas', 'frecuencia' => '5 horas', 'duracion' => '1 semana', 'instrucciones' => 'tomar cada 5 horas por 2 semanas', 'creado_en' => null],
    ['id' => 87, 'receta_id' => 48, 'medicamento_id' => 27, 'dosis' => '1 tableta', 'frecuencia' => '8 horas', 'duracion' => '3 semanas', 'instrucciones' => 'tomar cada', 'creado_en' => null],
    ['id' => 88, 'receta_id' => 49, 'medicamento_id' => 39, 'dosis' => '10 ml', 'frecuencia' => '2h', 'duracion' => '7 dias', 'instrucciones' => 'tomar la medicina cada 2 horas', 'creado_en' => null],
    ['id' => 89, 'receta_id' => 50, 'medicamento_id' => 4, 'dosis' => '222', 'frecuencia' => '222', 'duracion' => '22', 'instrucciones' => '22', 'creado_en' => null],
    ['id' => 90, 'receta_id' => 50, 'medicamento_id' => 11, 'dosis' => '22', 'frecuencia' => '22', 'duracion' => '22', 'instrucciones' => '22', 'creado_en' => null],
    ['id' => 91, 'receta_id' => 50, 'medicamento_id' => 39, 'dosis' => '222', 'frecuencia' => '222', 'duracion' => '22', 'instrucciones' => '222', 'creado_en' => null],
    ['id' => 92, 'receta_id' => 51, 'medicamento_id' => 2, 'dosis' => '11', 'frecuencia' => '11', 'duracion' => '11', 'instrucciones' => '11', 'creado_en' => null],
    ['id' => 93, 'receta_id' => 52, 'medicamento_id' => 17, 'dosis' => 'w', 'frecuencia' => 'w', 'duracion' => 'w', 'instrucciones' => 'w', 'creado_en' => null],
    ['id' => 94, 'receta_id' => 53, 'medicamento_id' => 9, 'dosis' => '1 tableta', 'frecuencia' => '12 horas', 'duracion' => '1 semana', 'instrucciones' => 'tomar una tableta cada 12 horas por una semana', 'creado_en' => null],
    ['id' => 95, 'receta_id' => 53, 'medicamento_id' => 16, 'dosis' => '1 tableta', 'frecuencia' => '8 horas', 'duracion' => '5 dias', 'instrucciones' => 'tomar una tableta cada 8 horas por 5 dias', 'creado_en' => null],
]);

    }
}
